[window]
option_as_alt = "OnlyLeft"
opacity = 0.7
blur = true

[font]
size = 12

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
